# Generated by Django 2.0.3 on 2018-03-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('from_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mailbox',
            name='messages',
            field=models.ManyToManyField(to='users.Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='mailbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MailBox'),
        ),
    ]
