# Generated by Django 2.0.3 on 2018-03-27 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_school', to='schools.Kindergarten')),
            ],
        ),
        migrations.AlterField(
            model_name='comparelist',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_school', to='schools.Kindergarten'),
        ),
        migrations.AlterField(
            model_name='comparelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='compare_schools',
            field=models.ManyToManyField(related_name='compare_kd', through='users.CompareList', to='schools.Kindergarten'),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='following_kd', through='users.FollowingList', to='schools.Kindergarten'),
        ),
    ]
