# Generated by Django 2.0.3 on 2018-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180327_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followinglist',
            name='school',
        ),
        migrations.RemoveField(
            model_name='followinglist',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='following_kd', to='schools.Kindergarten'),
        ),
        migrations.DeleteModel(
            name='FollowingList',
        ),
    ]
