# Generated by Django 2.0.3 on 2018-03-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MM',
            new_name='Message_Mailbox',
        ),
    ]
