# Generated by Django 2.0.2 on 2018-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Chinese', 'Chinese'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('Malay', 'Malay'), ('Arabic', 'Arabic')], max_length=20, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Playgroup', 'Playgroup'), ('Pre-Nursery', 'Pre-Nursery'), ('Kindergarten 1', 'Kindergarten 1'), ('Kindergarten 2', 'Kindergarten 2'), ('Nursery', 'Nursery')], max_length=20, verbose_name='Level')),
                ('vacancy', models.BooleanField(default=False, verbose_name='Vacancy Available')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(max_length=100, verbose_name='Centre Name')),
                ('centre_code', models.CharField(max_length=20, unique=True, verbose_name='Centre Code')),
                ('program_hours', models.CharField(max_length=100, verbose_name='Program Hour')),
                ('registration_fee', models.FloatField(verbose_name='Registration Fee')),
                ('fee', models.FloatField(verbose_name='Fees')),
                ('language_offer', models.ManyToManyField(to='schools.Language', verbose_name='Language Offered')),
            ],
            options={
                'verbose_name': 'Kindergarten',
                'verbose_name_plural': 'Kindergartens',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='kindergarten',
            field=models.ManyToManyField(to='schools.School', verbose_name='Kindergarten'),
        ),
    ]
