# Generated by Django 2.0.2 on 2018-03-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='kindergarten',
        ),
        migrations.RemoveField(
            model_name='school',
            name='language_offer',
        ),
        migrations.AddField(
            model_name='school',
            name='language',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('Malay', 'Malay'), ('Arabic', 'Arabic')], default='', max_length=20, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('Playgroup', 'Playgroup'), ('Pre-Nursery', 'Pre-Nursery'), ('Kindergarten 1', 'Kindergarten 1'), ('Kindergarten 2', 'Kindergarten 2'), ('Nursery', 'Nursery')], default='', max_length=20, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='school',
            name='vacancy',
            field=models.BooleanField(default=False, verbose_name='Vacancy Available'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
