# Generated by Django 2.0.2 on 2018-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20180303_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='centre_code',
            field=models.CharField(max_length=20, verbose_name='Centre Code'),
        ),
    ]
