# Generated by Django 2.0.2 on 2018-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20180303_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Centre Name')),
                ('isoperation', models.BooleanField(default=True, verbose_name='Operation Status')),
                ('type', models.CharField(choices=[('com', 'Commercial'), ('gov', 'Government')], max_length=50, verbose_name='Kindergarten Type')),
                ('address', models.CharField(max_length=100, verbose_name='Centre Address')),
                ('postalcode', models.IntegerField(verbose_name='Postal Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Centre Email Address')),
                ('website', models.URLField(verbose_name='Website')),
                ('number', models.IntegerField(verbose_name='Centre Contact Number')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('capacity', models.IntegerField(verbose_name='Accomodation Capacity')),
                ('outdoor', models.BooleanField(verbose_name='Provision of outdoor playground/garden')),
                ('bus', models.BooleanField(verbose_name='Bus Service')),
                ('sparkCer', models.BooleanField(verbose_name='SPARK Certified')),
                ('sparkvalidity', models.DateTimeField(verbose_name='SPARK Validity (end)')),
                ('registrationfee', models.IntegerField(verbose_name='Registration Fees')),
                ('k2fee', models.IntegerField(verbose_name='Kindergarten Two Fees')),
                ('k1fee', models.IntegerField(verbose_name='Kindergarten One Fees')),
                ('nurseryfee', models.IntegerField(verbose_name='Nursery Fees')),
                ('prenurseryfee', models.IntegerField(verbose_name='Pre-Nursery Fees')),
                ('playgroupfee', models.IntegerField(verbose_name='Playgroup Fees')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Chinese', 'Chinese'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('Malay', 'Malay'), ('Arabic', 'Arabic')], max_length=20, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='language',
            field=models.ManyToManyField(to='schools.Language', verbose_name='Language Offered'),
        ),
    ]
