# Generated by Django 2.0.2 on 2018-03-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20180318_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Website'),
        ),
    ]
