# Generated by Django 2.0.3 on 2018-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20180318_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindergarten',
            options={'verbose_name': 'Kindergarten', 'verbose_name_plural': 'Kindergarten'},
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='k1fee',
            field=models.CharField(max_length=10, verbose_name='Kindergarten One Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='k2fee',
            field=models.CharField(max_length=10, verbose_name='Kindergarten Two Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='nurseryfee',
            field=models.CharField(max_length=10, verbose_name='Nursery Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='playgroupfee',
            field=models.CharField(max_length=10, verbose_name='Playgroup Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='prenurseryfee',
            field=models.CharField(max_length=10, verbose_name='Pre-Nursery Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='registrationfee',
            field=models.CharField(max_length=10, verbose_name='Registration Fees'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='sparkvalidity',
            field=models.CharField(max_length=100, verbose_name='SPARK Validity (end)'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Kindergarten Type'),
        ),
    ]
